// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package gowsdl

var schemaHeader = `
// Code generated by gowsdl DO NOT EDIT.
package {{goPackage}}

import (
	{{goImports}}
)

`

var schemaTmpl = `
{{ $targetNamespace := .TargetNamespace }}

{{define "SimpleType"}}
	{{$typeName := findTypeName .Name }}
	{{if .Doc}} {{.Doc | comment}} {{end}}
	{{if ne .List.ItemType ""}}
		type {{$typeName}} []{{findTypeNillable .List.ItemType true }}
	{{else if ne .Union.MemberTypes ""}}
		type {{$typeName}} string
	{{else if .Union.SimpleType}}
		type {{$typeName}} string
	{{else if .Restriction.Base}}
		type {{$typeName}} {{findTypeNillable .Restriction.Base true }}
    {{else}}
		type {{$typeName}} interface{}
	{{end}}

	{{if .Restriction.Enumeration}}
	const (
		{{with .Restriction}}
			{{range .Enumeration}}
				{{if .Doc}} {{.Doc | comment}} {{end}}
				{{$typeName}}{{$value := findTypeName .Value}} {{$typeName}} = "{{goString .Value}}" {{end}}
		{{end}}
	)
	{{end}}
{{end}}

{{define "ComplexContent"}}
	{{$baseType := findTypeNillable .Extension.Base true}}
	{{ if $baseType }}
		{{$baseType}}
	{{end}}

	{{template "Elements" .Extension.Sequence}}
	{{template "Elements" .Extension.Choice}}
	{{template "Elements" .Extension.SequenceChoice}}
	{{template "Attributes" .Extension.Attributes}}
{{end}}

{{define "Attributes"}}
    {{ $targetNamespace := getNS }}
	{{range .}}
		{{if .Doc}} {{.Doc | comment}} {{end}}
		{{ if ne .Type "" }}
			{{ normalize .Name | makeFieldPublic}} {{findTypeNillable .Type false}} ` + "`" + `xml:"{{.Name}},attr,omitempty" json:"{{.Name}},omitempty"` + "`" + `
		{{ else }}
			{{ normalize .Name | makeFieldPublic}} string ` + "`" + `xml:"{{.Name}},attr,omitempty" json:"{{.Name}},omitempty"` + "`" + `
		{{ end }}
	{{end}}
{{end}}

{{define "SimpleContent"}}
	Value {{findTypeNillable .Extension.Base true}} ` + "`xml:\",chardata\" json:\"-,\"`" + `
	{{template "Attributes" .Extension.Attributes}}
{{end}}

{{define "ComplexTypeInline"}}
	{{findTypeName .Name }} {{if eq .MaxOccurs "unbounded"}}[]{{end}}struct {
	{{with .ComplexType}}
		{{if ne .ComplexContent.Extension.Base ""}}
			{{template "ComplexContent" .ComplexContent}}
		{{else if ne .SimpleContent.Extension.Base ""}}
			{{template "SimpleContent" .SimpleContent}}
		{{else}}
			{{template "Elements" .Sequence}}
			{{template "Elements" .Choice}}
			{{template "Elements" .SequenceChoice}}
			{{template "Elements" .All}}
			{{template "Attributes" .Attributes}}
		{{end}}
	{{end}}
	} ` + "`" + `xml:"{{.Name}},omitempty" json:"{{.Name}},omitempty"` + "`" + `
{{end}}

{{define "Elements"}}
	{{range .}}
		{{if ne .Ref ""}}
			{{removeNS .Ref | replaceReservedWords  | makePublic}} {{if eq .MaxOccurs "unbounded"}}[]{{end}}{{findTypeNillable .Ref true }} ` + "`" + `xml:"{{.Ref | removeNS}},omitempty" json:"{{.Ref | removeNS}},omitempty"` + "`" + `
		{{else}}
		{{if not .Type}}
			{{if .SimpleType}}
				{{if .Doc}} {{.Doc | comment}} {{end}}
				{{if ne .SimpleType.List.ItemType ""}}
					{{ normalize .Name | makeFieldPublic}} []{{findTypeNillable .SimpleType.List.ItemType true}} ` + "`" + `xml:"{{.Name}},omitempty" json:"{{.Name}},omitempty"` + "`" + `
				{{else}}
					{{ normalize .Name | makeFieldPublic}} {{findTypeNillable .SimpleType.Restriction.Base true}} ` + "`" + `xml:"{{.Name}},omitempty" json:"{{.Name}},omitempty"` + "`" + `
				{{end}}
			{{else}}
				{{template "ComplexTypeInline" .}}
			{{end}}
		{{else}}
			{{if .Doc}}{{.Doc | comment}} {{end}}
			{{replaceAttrReservedWords .Name | makeFieldPublic}} {{if eq .MaxOccurs "unbounded"}}[]{{end}}{{findTypeNillable .Type true }} ` + "`" + `xml:"{{.Name}},omitempty" json:"{{.Name}},omitempty"` + "`" + ` {{end}}
		{{end}}
	{{end}}
{{end}}

{{define "Any"}}
	{{range .}}
		Items     []string ` + "`" + `xml:",any" json:"items,omitempty"` + "`" + `
	{{end}}
{{end}}

{{range .SimpleType}}
	{{template "SimpleType" .}}
{{end}}

{{range .Elements}}
	{{$name := .Name }}
	{{$typeName := findTypeName .Name }}
	{{if not .Type}}
		{{/* ComplexTypeLocal */}}
		{{with .ComplexType}}
			type {{$typeName}} struct {
				XMLName xml.Name
				{{if ne .ComplexContent.Extension.Base ""}}
					{{template "ComplexContent" .ComplexContent}}
				{{else if ne .SimpleContent.Extension.Base ""}}
					{{template "SimpleContent" .SimpleContent}}
				{{else}}
					{{template "Elements" .Sequence}}
					{{template "Any" .Any}}
					{{template "Elements" .Choice}}
					{{template "Elements" .SequenceChoice}}
					{{template "Elements" .All}}
					{{template "Attributes" .Attributes}}
				{{end}}
			}
			func New{{$typeName}}() *{{$typeName}} {
				return &{{$typeName}}{XMLName: xml.Name{Space: "{{$targetNamespace}}", Local: "{{$name}}"}}
			}
		{{end}}
		{{/* SimpleTypeLocal */}}
		{{with .SimpleType}}
			{{if .Doc}} {{.Doc | comment}} {{end}}
			{{if ne .List.ItemType ""}}
				type {{$typeName}} []{{findTypeNillable .List.ItemType true }}
			{{else if ne .Union.MemberTypes ""}}
				type {{$typeName}} string
			{{else if .Union.SimpleType}}
				type {{$typeName}} string
			{{else if .Restriction.Base}}
				type {{$typeName}} {{findTypeNillable .Restriction.Base true }}
			{{else}}
				type {{$typeName}} interface{}
			{{end}}

			{{if .Restriction.Enumeration}}
			const (
				{{with .Restriction}}
					{{range .Enumeration}}
						{{if .Doc}} {{.Doc | comment}} {{end}}
						{{$typeName}}{{$value := findTypeName .Value}} {{$typeName}} = "{{goString .Value}}" {{end}}
				{{end}}
			)
			{{end}}
		{{end}}
	{{else}}
		{{$type := findTypeNillable .Type .Nillable}}
		{{if ne ($typeName) ($type)}}
			type {{$typeName}} {{$type}}
			{{if eq ($type) ("soap.XSDDateTime")}}
				func (xdt {{$typeName}}) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
					return soap.XSDDateTime(xdt).MarshalXML(e, start)
				}

				func (xdt *{{$typeName}}) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
					return (*soap.XSDDateTime)(xdt).UnmarshalXML(d, start)
				}
			{{else if eq ($type) ("soap.XSDDate")}}
				func (xd {{$typeName}}) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
					return soap.XSDDate(xd).MarshalXML(e, start)
				}

				func (xd *{{$typeName}}) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
					return (*soap.XSDDate)(xd).UnmarshalXML(d, start)
				}
			{{else if eq ($type) ("soap.XSDTime")}}
				func (xt {{$typeName}}) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
					return soap.XSDTime(xt).MarshalXML(e, start)
				}

				func (xt *{{$typeName}}) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
					return (*soap.XSDTime)(xt).UnmarshalXML(d, start)
				}
			{{end}}
		{{end}}
	{{end}}
{{end}}

{{range .ComplexTypes}}
	{{/* ComplexTypeGlobal */}}
	{{$name := .Name }}
	{{$typeName := findTypeName .Name }}
	{{ log "generate complex type" .Name "as" $typeName }}
	{{if and (eq (len .SimpleContent.Extension.Attributes) 0) (eq (findTypeNillable .SimpleContent.Extension.Base true) "string") }}
		type {{$typeName}} string
	{{else}}
		type {{$typeName}} struct {
				XMLName xml.Name
			{{if ne .ComplexContent.Extension.Base ""}}
				{{template "ComplexContent" .ComplexContent}}
			{{else if ne .SimpleContent.Extension.Base ""}}
				{{template "SimpleContent" .SimpleContent}}
			{{else}}
				{{template "Elements" .Sequence}}
				{{template "Any" .Any}}
				{{template "Elements" .Choice}}
				{{template "Elements" .SequenceChoice}}
				{{template "Elements" .All}}
				{{template "Attributes" .Attributes}}
			{{end}}
		}

		func New{{$typeName}}() *{{$typeName}} {
			return &{{$typeName}}{XMLName: xml.Name{Space: "{{$targetNamespace}}", Local: "{{$name}}"}}
		}
	{{end}}
{{end}}

`
