// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package gowsdl

var typesResolvers = `
// Code generated by gowsdl DO NOT EDIT.
{{ $go_package := GoPackage }}
package {{ $go_package }}

import (
	"github.com/hooklift/gowsdl/common"
)

var NamespacesTypes *common.NamespaceTypes

func init() {
	var types *common.Types
{{- range $key, $types := .NamespaceToResolver }}
{{ if eq $types.GoPackage $go_package }}
	types = NamespacesTypes.Register("{{ $key }}")
{{ range $typeName, $goType := $types.NameToGoType }}{{ if $typeName }}
	types.Register("{{ $typeName }}", (*{{ $goType }})(nil))
{{- end -}}
{{ end -}}
{{- end -}}
{{- end -}}}
`
