// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package gowsdl

var typesResolvers = `
// Code generated by gowsdl DO NOT EDIT.
package {{ goPackage }}

import (
	"{{ goPackageBase }}"
)

func init() {
{{- range $key, $types := . }}
	types := ws.NamespacesTypes.Register("{{ $key }}")
{{ range $typeName, $goType := $types }}
	types.Register("{{ $typeName }}", func() (interface{}, *xml.Name) {
		item := New{{ $goType }}()
		return item, &item.XMLName
	})
{{- end -}}
{{- end -}}}
`
